server:
  port: 8091
flyway:
  enabled: false
endpoints.health.sensitive: false
spring:
  application:
    name: batch-metrics
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.freemarker.checkTemplateLocation: false
ENVIRONMENT: h2
server.servletPath: /*
spring.batch.job.enabled: false